default:
  - build:
      - checkGivenSemanticVersion:
          - checkSemanticVersion:
      - getSemanticVersion:
          - gitCalculateSemanticVersion:
      - getImageName:
          - containerConstructImageName:
      - artifacts:
          - containerBuildImage:
              imageName: ${var.containerImageName}
              imageTag: ${var.semanticVersion}
              pullAlways: false
  - test:
      - unit:
          - pythonContainerTest:
              imageName: ${var.containerImageName}
              imageTag: ${var.semanticVersion}
              pullAlways: false
              commands: >
              packageManager: ''
              removeLocalImage: false
      - lint:
          - pythonContainerLint:
              pullAlways: false
              removeLocalImage: false
          - pythonContainerTypeCheck:
              pullAlways: false
              removeLocalImage: false
  - verify:
      - securityScan:
          - securityGenerateSbom:
              target: file://poetry.lock
          - securityVulnerabilityScan:
              format: [ 'html', 'print' ]
              severity: [ 'CRITICAL', 'HIGH' ]
              outputPrefix: sbom
  - publish:
      - pypi:
          - pythonContainerBuildAndPublishPackage:
              pullAlways: false
              version: ${var.semanticVersion}
      - docs:
          - openshiftPublishDocs:
              docSrc: doc/_build/
              docType: python

# Alternative setup for installing and testing the service locally using the system's Python environment.
local:
  - build:
      - install:
          - pythonLocalInstall:
      - docs:
          - pythonLocalDocs:
      - format:
          - pythonLocalFormat:
              inPlace: true
  - test:
      - unit:
          - pythonLocalTest:
      - lint:
          - pythonLocalLint:
          - pythonLocalTypeCheck:

variables:
  solution: numericalweatherpredictions
  project: fdb-utils
  notifyOnNightlyFailure: p_polytope@meteoswiss.ch
  semanticVersion: 0.0.0
